micronaut:
  server:
    port: 8081
    cors:
      enabled: false
      web:
        allowedOrigins:
          http://localhost:4200/
        allowedMethods:
          - POST
          - PUT
          - GET
        exposedHeaders:
          - Content-Type
          - Authorization


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '4545'
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
jpa.default.properties.hibernate.hbm2ddl.auto: update
